### ISSUE TITLE
[Bug] Output console not toggle in Build 3124

### ISSUE THREAD

**Issue by Kristinita** [albertosantini/sublimetext-buildnext#8]
### Summary

Everything worked fine until yesterday, but after upgrading to Build 3124 output console not toggle now.

### Expected behavior

Toggle output console after successfully completed compilation.

### Actual behavior

Not toggle output console after successfully completed compilation.

### Steps to reproduce

For example, my `slim.build-system` file:
```

{
    "cmd": [
        "slimrb"
    ],
    "selector": "text.slim",
    "syntax": "Packages/ANSIescape/ANSI.tmLanguage",
    "target": "ansi_color_build",
    "windows": {
        "cmd": [
            "slimrb",
            "-p",
            "--trace",
            "$file",
            "$file_base_name.html"
        ],
        "shell": true
    },
    "working_dir": "${file_path:${folder}}"
}
```

I press <kbd>Ctrl+B</kbd>, when I is situated on my `.slim` file, but output console now not toggle for me:

![Output console](http://i.imgur.com/ryh3LuW.png)

Also I opened the console, sometimes there are displayed error.

```
key evt: control+c
command: copy_edit
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "BuildNext in E:\Sublime Text 3\Data\Installed Packages\Build Next.sublime-package", line 35, in run
TypeError: run() got multiple values for argument 'update_phantoms_only'
```

### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3124

Thanks.

**Comment by albertosantini** [comment]
Thanks for the feedback.

It is due to the new signature `ExecCommand.run`.

Preparing a fix.

**Comment by albertosantini** [comment]
Published 1.4.0.

**Comment by Kristinita** [comment]
@albertosantini After upgrade Build Next problem #9 successfully solved for me, but this problem not solved.

Now I no get stack trace, but output console still not toggle after successfully completed compilation.

Thanks.

**Comment by albertosantini** [comment]
Weirdly.

I checked it again with a few build systems and it seems the plugin works correctly.
When there is not any error, the output console is closed.

Exceptionally I tried to reproduce your use case with Ruby and slim build system.

```
{
    "cmd": [
        "slimrb"
    ],
    "selector": "text.slim",
    "windows": {
        "cmd": [
            "ruby",
            "c:\\My\\Dev\\snippets\\slim\\bin\\slimrb",
            "-p",
            "--trace",
            "$file",
            "$file_base_name.html"
        ],
        "shell": true
    },
    "working_dir": "${file_path:${folder}}"
}
```

I tested it on `slim\test\include\files\slimfile.slim` and `slim\test\include\files\subdir\test.slim` and the output console is closed correctly. If I add random chars in the slim file, just to invalidate the content, the output console gets opened due to the errors.

So I cannot reproduce your use case.

**Comment by Kristinita** [comment]
@albertosantini , I'm sorry, you testing with [SublimeANSI](https://github.com/aziz/SublimeANSI) package? I install SublimeANSI and [add](https://github.com/aziz/SublimeANSI#using-this-plugin-as-a-dependency-for-your-pluginbuild-output-panel) 2 lines in my `.sublime-build ` file:

            "target": "ansi_color_build",
            "syntax": "Packages/ANSIescape/ANSI.tmLanguage"

My .sublime-build file now is:

```
{
    "cmd": [
        "slimrb"
    ],
    "selector": "text.slim",
    "syntax": "Packages/ANSIescape/ANSI.tmLanguage",
    "target": "ansi_color_build",
    "windows": {
        "cmd": [
            "slimrb",
            "-p",
            "--trace",
            "$file",
            "$file_base_name.html"
        ],
        "shell": true
    },
    "working_dir": "${file_path:${folder}}"
}
```

Without SublimeANSI Build Next works good, but with SublimeANSI Build Next works good before last upgrade Sublime Text.

Thanks.

**Comment by albertosantini** [comment]
I tested it with SublimeANSI package installed and I added `"syntax": "Packages/ANSIescape/ANSI.tmLanguage"` line to the build system.

It works correctly as expected: it toggles correctly the output view.

Eventually, as in your build file, I added the line `"target": "ansi_color_build"` and I **reproduced** the issue.

That target overrides the default one `exec`: that executes methods in `AnsiColorBuildCommand` class of the SublimeAnsi package and not the ones in `ExecCommand` class of Build Next package.

Indeed Build Next works if you use the default target `exec` and not `ansi_color_build` one.

You can try yourself what it happens with the snippet below.
If you create the following snippet `Packages/User/z.py` and you use `"target": "foo"` or `"target": "bar"` in the build system file, when you execute the build system, you can notice in the console it is printed FOO or BAR, depending on the target; no other on_finished method is called, Build Next or SublimeAnsi.

```
# paste this in z.py
import Default

class FooCommand(Default.exec.ExecCommand):
    def on_finished(self, proc):
        super(FooCommand, self).on_finished(proc)
        print("FOO")

class BarCommand(Default.exec.ExecCommand):
    def on_finished(self, proc):
        super(BarCommand, self).on_finished(proc)
        print("BAR")
```

I tried the script above with the previous beta 3114, and the behaviour is the same I saw in the latest beta 3124.

Are you sure it worked correctly before the update? 

No idea because it worked before the update and no idea how to fix it or if there is something wrong in Build Next package or in SublimeANSI one (or in neither packages, because it is the expected python behaviour and there was a bug, actually fixed, in ST3).

Maybe ST might support multiple targets: like  `"targets": ["ansi_color_build", "build_next"]`.
Don't hold the breath.

As workaround, if you use Build Next only to close the output view if there are no errors, you may suggest a PR to SublimeANSI:

```
# to add in on_finished method, AnsiColorBuildCommand class
# https://github.com/aziz/SublimeANSI/blob/master/ansi.py#L357
...
        exit_code = proc.exit_code()
        errors_len = len(self.output_view.find_all_results())

        if (exit_code != None and exit_code != 0) or errors_len > 0:
            self.window.run_command("show_panel", {"panel": "output.exec"})
        else:
            self.window.run_command("hide_panel", {"panel": "output.exec"})
...
```

Hope my details may help to clarify the issue. 
Feel free to contribute here or in SublimeANSI. Thanks.
